# Generated by Django 3.1.5 on 2021-03-29 07:32

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('ph_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('msg', models.TextField(max_length=500)),
            ],
            options={
                'db_table': 'contact_form',
            },
        ),
        migrations.CreateModel(
            name='Myadm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='upload_img')),
            ],
            options={
                'db_table': 'Adm_handle',
            },
        ),
    ]
