# Generated by Django 3.1.5 on 2021-04-16 07:02

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('rest_proj_app', '0002_auto_20210329_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(default='', max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('ph_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('address', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'Order_db',
            },
        ),
    ]
